# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  lwr_arm_0_joint:
    has_velocity_limits: true
    max_velocity: 1.91986217719
    has_acceleration_limits: false
    max_acceleration: 0
  lwr_arm_1_joint:
    has_velocity_limits: true
    max_velocity: 1.91986217719
    has_acceleration_limits: false
    max_acceleration: 0
  lwr_arm_2_joint:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: false
    max_acceleration: 0
  lwr_arm_3_joint:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: false
    max_acceleration: 0
  lwr_arm_4_joint:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: false
    max_acceleration: 0
  lwr_arm_5_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  lwr_arm_6_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0